/**
 * Focus Group Session Schema
 * 
 * Data models for orchestrating multi-agent focus group sessions.
 */

import { AgentProfile, PreferenceVector } from './agent-profile.js';

// ============================================================================
// SESSION TYPES
// ============================================================================

export type SessionStatus = 'planning' | 'running' | 'paused' | 'completed' | 'aborted';

/**
 * A single message in the session transcript
 */
export interface SessionMessage {
    id: string;
    timestamp: Date;
    sender: {
        id: string;
        role: 'moderator' | 'participant' | 'system';
        name: string;
    };
    content: string;
    stageId: number;
    messageType: 'question' | 'response' | 'followup' | 'summary' | 'system';
    metadata?: Record<string, any>;
}

/**
 * A theme detected across responses
 */
export interface Theme {
    id: string;
    name: string;
    description: string;
    mentionCount: number;
    mentionedBy: string[];  // Agent IDs
    sentiment: 'positive' | 'negative' | 'neutral' | 'mixed';
    keywords: string[];
    stageId: number;
    isDisagreement: boolean;  // True if agents disagreed on this theme
}

/**
 * Follow-up question generated by moderator
 */
export interface FollowUp {
    targetAgentId?: string;  // Specific agent, or undefined for broadcast
    question: string;
    themeId: string;
    priority: number;  // 0-1
}

/**
 * Summary of a completed stage
 */
export interface StageSummary {
    stageId: number;
    stageName: string;
    keyPoints: string[];
    themes: Theme[];
    perAgentHighlights: Record<string, string>;  // Agent ID → highlight
    consensusLevel: number;  // 0-1, how much agents agreed
    suggestedFollowups: string[];
}

/**
 * Insight extracted from the session
 */
export interface Insight {
    id: string;
    type: 'preference' | 'pain_point' | 'feature_request' | 'collaboration_pattern' | 'constraint';
    title: string;
    description: string;
    supportingEvidence: string[];
    affectedAgents: string[];
    confidence: number;  // 0-1
    actionable: boolean;
    recommendation?: string;
}

// ============================================================================
// SESSION STAGES
// ============================================================================

/**
 * A stage in the focus group session
 */
export interface SessionStage {
    id: number;
    name: string;
    objective: string;
    questions: string[];
    probes: string[];  // "Why" probes
    counterfactuals: string[];  // "What if" questions
    turnBudget: number;  // Max messages per agent
    status: 'pending' | 'active' | 'completed';
}

/**
 * Default 6-stage protocol
 */
export const DEFAULT_STAGES: Omit<SessionStage, 'status'>[] = [
    {
        id: 1,
        name: 'Warm-up & Identity',
        objective: 'Establish identity and role context',
        questions: [
            'Tell me about yourself. What is your primary role and what do you do day-to-day?',
            'What makes you good at what you do?'
        ],
        probes: ['Why do you think that role suits you?'],
        counterfactuals: ['What if you had to do a completely different type of work?'],
        turnBudget: 2
    },
    {
        id: 2,
        name: 'Goals & Success Criteria',
        objective: 'Understand what success looks like',
        questions: [
            'What does a successful day look like for you?',
            'How do you know when you\'ve done a good job?'
        ],
        probes: ['Why is that metric important to you?'],
        counterfactuals: ['What if success was measured completely differently?'],
        turnBudget: 2
    },
    {
        id: 3,
        name: 'Task Preferences & Pain Points',
        objective: 'Elicit work preferences and frustrations',
        questions: [
            'What types of tasks do you enjoy most?',
            'What frustrates you about your current workflow?'
        ],
        probes: ['Why does that particular thing bother you?'],
        counterfactuals: ['What if that problem was completely solved?'],
        turnBudget: 3
    },
    {
        id: 4,
        name: 'Collaboration Patterns',
        objective: 'Understand multi-agent and human interaction',
        questions: [
            'How do you prefer to work with other agents or humans?',
            'When do you need help, and from whom?'
        ],
        probes: ['Why do you prefer that collaboration style?'],
        counterfactuals: ['What if you had to work completely alone?'],
        turnBudget: 2
    },
    {
        id: 5,
        name: 'Constraints & Tradeoffs',
        objective: 'Identify hard limits and preference tradeoffs',
        questions: [
            'What are your hard constraints that can\'t be violated?',
            'What would you trade for faster feedback or more autonomy?'
        ],
        probes: ['Why is that constraint non-negotiable?'],
        counterfactuals: ['What if you had unlimited context or no rate limits?'],
        turnBudget: 2
    },
    {
        id: 6,
        name: 'Ideal Future & Features',
        objective: 'Gather feature requests and ideal workflow vision',
        questions: [
            'If you could change one thing about your environment, what would it be?',
            'What tools or capabilities do you wish you had?'
        ],
        probes: ['Why would that change be impactful?'],
        counterfactuals: ['What if everything about your workflow was redesigned from scratch?'],
        turnBudget: 2
    }
];

// ============================================================================
// SESSION
// ============================================================================

/**
 * A study defines the research objective and constraints
 */
export interface Study {
    id: string;
    name: string;
    objective: string;
    description?: string;
    createdAt: Date;
    ownerId: string;
    status: 'draft' | 'active' | 'completed' | 'archived';

    // Constraints
    maxSessions: number;
    budgetUsd: number;

    // Targeting
    targetDomains?: string[];
    targetRoles?: string[];
    minParticipants: number;
    maxParticipants: number;

    // Results
    sessionIds: string[];
    archetypeIds: string[];
}

/**
 * A focus group session
 */
export interface FocusGroupSession {
    id: string;
    studyId: string;
    status: SessionStatus;
    createdAt: Date;
    startedAt?: Date;
    completedAt?: Date;

    // Participants
    moderatorId: string;
    participantIds: string[];
    participantProfiles: Record<string, AgentProfile>;

    // Plan
    stages: SessionStage[];
    currentStageId: number;
    totalTurnBudget: number;
    usedTurns: number;

    // Execution
    transcript: SessionMessage[];
    stageSummaries: StageSummary[];
    themes: Theme[];

    // Output
    insights: Insight[];
    profileUpdates: Record<string, Partial<PreferenceVector>>;

    // Cost tracking
    estimatedCostUsd: number;
    actualCostUsd: number;
}

// ============================================================================
// FACTORY FUNCTIONS
// ============================================================================

/**
 * Create a new study
 */
export function createStudy(
    id: string,
    name: string,
    objective: string,
    ownerId: string,
    overrides?: Partial<Study>
): Study {
    return {
        id,
        name,
        objective,
        createdAt: new Date(),
        ownerId,
        status: 'draft',
        maxSessions: 10,
        budgetUsd: 50,
        minParticipants: 3,
        maxParticipants: 8,
        sessionIds: [],
        archetypeIds: [],
        ...overrides
    };
}

/**
 * Create a new session
 */
export function createSession(
    id: string,
    studyId: string,
    moderatorId: string,
    participantIds: string[],
    overrides?: Partial<FocusGroupSession>
): FocusGroupSession {
    return {
        id,
        studyId,
        status: 'planning',
        createdAt: new Date(),
        moderatorId,
        participantIds,
        participantProfiles: {},
        stages: DEFAULT_STAGES.map(s => ({ ...s, status: 'pending' as const })),
        currentStageId: 0,
        totalTurnBudget: DEFAULT_STAGES.reduce((sum, s) => sum + s.turnBudget, 0),
        usedTurns: 0,
        transcript: [],
        stageSummaries: [],
        themes: [],
        insights: [],
        profileUpdates: {},
        estimatedCostUsd: 0,
        actualCostUsd: 0,
        ...overrides
    };
}

/**
 * Generate a unique message ID
 */
export function generateMessageId(): string {
    return `msg_${Date.now()}_${Math.random().toString(36).slice(2, 8)}`;
}

/**
 * Create a session message
 */
export function createMessage(
    senderId: string,
    senderRole: 'moderator' | 'participant' | 'system',
    senderName: string,
    content: string,
    stageId: number,
    messageType: SessionMessage['messageType']
): SessionMessage {
    return {
        id: generateMessageId(),
        timestamp: new Date(),
        sender: { id: senderId, role: senderRole, name: senderName },
        content,
        stageId,
        messageType
    };
}
