import { describe, expect, it, vi } from 'vitest';
import { lemmaService } from '../../src/services/LemmaService.js';
import { createHash } from 'crypto';
import { redis } from '../../src/lib/redis.js';

vi.mock('../../src/lib/llm/factory.js', () => ({
    LLMFactory: {
        createProvider: () => ({
            chat: async (messages: any[]) => ({
                content: `MOCKED_EXECUTION: ${JSON.stringify(messages)}`,
                usage: { prompt_tokens: 10, completion_tokens: 10, total_tokens: 20 }
            })
        })
    }
}));

function unique(prefix: string) {
    return `${prefix}-${Date.now()}-${Math.random().toString(36).slice(2, 8)}`;
}

describe.sequential('Lemma Caching Engine', () => {

    it('resolves independent lemmas, hits cached overlaps, and synthesizes', async () => {
        const uniqueFact = unique('fact');
        const uniqueCode = unique('code');

        const subtasks = [
            { id: "step_1", description: `Explain the concept of ${uniqueFact}` },
            { id: "step_2", description: `Write a Javascript function printing ${uniqueCode}` }
        ];

        // 1. Pre-warm the cache for step_1 to simulate a mathematical overlap
        const normalized = subtasks[0].description.trim().toLowerCase();
        const hash = createHash('sha256').update(normalized).digest('hex');
        await redis.set(`lemma:cache:v1:${hash}`, `CACHED_RESPONSE_FOR_FACT_${uniqueFact}`);

        // 2. Resolve lemmas (parallel execution)
        const { results, metrics } = await lemmaService.resolve(subtasks, 'openai', 'gpt-4o-mini');

        expect(metrics.hits).toBe(1);
        expect(metrics.misses).toBe(1);

        // Step 1 should be perfectly fetched from the cache
        expect(results['step_1']).toBe(`CACHED_RESPONSE_FOR_FACT_${uniqueFact}`);

        // Step 2 should be newly generated by the LLM
        expect(results['step_2']).toContain(uniqueCode);

        // 3. Synthesize
        const synthesis = await lemmaService.synthesize(`Combine the fact and the script`, results, 'openai', 'gpt-4o-mini');

        // The final synthesized answer should contain elements from both the cached hit and the generated miss
        expect(synthesis).toContain(`CACHED_RESPONSE_FOR_FACT_${uniqueFact}`);
        expect(synthesis).toContain(uniqueCode);
    }, 20000);
});
